/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    __TPM_HASH_DATA_FP_H_
#define    __TPM_HASH_DATA_FP_H_

// This function is called to process a _TPM_Hash_Data indication.
LIB_EXPORT void
_TPM_Hash_Data(
    uint32_t         dataSize,      // IN: size of data to be extend
    unsigned char   *data           // IN: data buffer
    );


#endif  // __TPM_HASH_DATA_FP_H_
