/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _ALGORITHMTESTS_FP_H_
#define    _ALGORITHMTESTS_FP_H_

#ifdef SELF_TEST
//*** TestAlgorithm()
// Dispatches to the correct test function for the algorithm. If algorithm is not
// If 'toTest' is not NULL, then the test decisions are based on the algorithm
// selections in 'toTest'. Otherwise, 'g_toTest' is used. When bits are clear in
// 'g_toTest' they will also be cleared 'toTest'.
// If there doesn't happen to be a test for the algorithm, its associated bit
// quietly cleared.
// If 'alg' is zero (TPM_ALG_ERROR), then the toTest vector is cleared of any bits
// for which there is a test (i.e. no tests are actually run but the vector is
// cleared.
// Note: 'toTest' will only ever have bits set for implemented algorithms but 'alg'
// can be anything.
// return type: TPM_RC
//  TPM_RC_SUCCESS      test complete
//  TPM_RC_CANCELED     test was canceled
LIB_EXPORT
TPM_RC
TestAlgorithm(
    TPM_ALG_ID               alg,
    ALGORITHM_VECTOR        *toTest
    );
#endif // SELF_TESTS


#endif  // _ALGORITHMTESTS_FP_H_
