/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _COMMANDDISPATCHER_FP_H_
#define    _COMMANDDISPATCHER_FP_H_

#ifdef  TABLE_DRIVEN_DISPATCH  //%
#endif

//** Marshal/Unmarshal Functions

//*** ParseHandleBuffer()
// This is the table-driven version of the handle buffer unmarshaling code
TPM_RC
ParseHandleBuffer(
    COMMAND                 *command
    );

TPM_RC
CommandDispatcher(
    COMMAND                 *command
    );


#endif  // _COMMANDDISPATCHER_FP_H_
