/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _GLOBAL_FP_H_
#define    _GLOBAL_FP_H_

#if 0
#endif // 0


#endif  // _GLOBAL_FP_H_
