/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _MSBNMALLOC_FP_H_
#define    _MSBNMALLOC_FP_H_

#if MATH_LIB == MSBN

#ifdef COLLECT_METRICS
//*** FindMetric()
// This is called when a context is created for a function. It searches to find the
// function name and if found, it associates the context address with the name. This
// allows the entry to be found using the
memoryMetric *
FindMetric(
    LPCSTR           name
    );
#endif
// The context structures are contained in the caller's space. This function links
// and initializes them.
//

//*** MsBnContextStart()
pMsbnCtx
MsBnContextStart(
    LPCSTR               name,
    crypt_uword_t       *pool,      // IN: the data pool for temps
    size_t               uwords     // IN: number of crypt_uwords in 'pool'
    );

void* WINAPI mp_alloc_temp(
    DWORDREGC cb,
    LPCSTR    pszSource_info,
    bigctx_t  *pCtx);

void WINAPI mp_free_temp(
    __in                  void     *pVoid,
    __in_opt              LPCSTR    pszSource_info,
    __in                  bigctx_t  *pCtx);

void WINAPI SetMpErrno(mp_errno_tc code, bigctx_t *pBignumCtxt);

void WINAPI SetMpErrno_clue1(__in mp_errno_tc code, __in_opt const char *hint,
                             PBIGCTX_ARG);
#endif


#endif  // _MSBNMALLOC_FP_H_
