/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _PRIMEDATA_FP_H_
#define    _PRIMEDATA_FP_H_



#endif  // _PRIMEDATA_FP_H_
