/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _TPMTOLTCDESSUPPORT_FP_H_
#define    _TPMTOLTCDESSUPPORT_FP_H_

#if SYM_LIB == LTC && defined TPM_ALG_TDES
//** TDES_setup
// This function calls the LTC function to generate a TDES key schedule. If the
// key is one DES key (8 bytes), then it is replicated two more times to create a
// 24-byte TDES key. If the key is two key (16 bytes), then the first DES key is
// replicated to the third key position.
void TDES_setup(
    const BYTE          *key,
    UINT32               keyBits,
    symmetric_key       *skey
    );
#endif


#endif  // _TPMTOLTCDESSUPPORT_FP_H_
