/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    __TPM_HASH_START_FP_H_
#define    __TPM_HASH_START_FP_H_

// This function is called to process a _TPM_Hash_Start indication.
LIB_EXPORT void
_TPM_Hash_Start(
    void
    );


#endif  // __TPM_HASH_START_FP_H_
