/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _RESPONSECODEPROCESSING_FP_H_
#define    _RESPONSECODEPROCESSING_FP_H_

//** RcSafeAddToResult()
// Adds a modifier to a response code as long as the response code allows a modifier
// and no modifier has already been added.
#ifdef INLINE_FUNCTIONS
#define INLINE_RcSafeAddToResult
#endif

#ifndef INLINE_RcSafeAddToResult
TPM_RC
RcSafeAddToResult(
    TPM_RC          responseCode,
    TPM_RC          modifier
    );
#else
INLINE TPM_RC
RcSafeAddToResult(
    TPM_RC          responseCode,
    TPM_RC          modifier
    )
{
    if((responseCode & RC_FMT1) && !(responseCode & 0xf40))
       return responseCode + modifier;
    else
        return responseCode;
}
#endif // INLINE_RcSafeAddToResult


#endif  // _RESPONSECODEPROCESSING_FP_H_
