/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _RESPONSE_FP_H_
#define    _RESPONSE_FP_H_

//** BuildResponseHeader()
// Adds the reponse header to the response. It will update command->parameterSize
// to indicate the total size of the response.
void
BuildResponseHeader(
    COMMAND         *command,       // IN: main control structure
    BYTE            *buffer,        // OUT: the output buffer
    TPM_RC           result         // IN: the response code
    );


#endif  // _RESPONSE_FP_H_
