/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _RSAKEYCACHE_FP_H_
#define    _RSAKEYCACHE_FP_H_

#if defined SIMULATION && defined USE_RSA_KEY_CACHE
//*** RsaKeyCacheControl()
// Used to enable and disable the RSA key cache.
LIB_EXPORT void
RsaKeyCacheControl(
    int             state
    );

BOOL
GetCachedRsaKey(
    OBJECT              *key,
    RAND_STATE          *rand               // IN: if not NULL, the deterministic
                                            //     RNG state
    );
#endif  // defined SIMULATION && defined USE_RSA_KEY_CACHE


#endif  // _RSAKEYCACHE_FP_H_
