/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _TPMSIZECHECKS_FP_H_
#define    _TPMSIZECHECKS_FP_H_

#ifdef RUNTIME_SIZE_CHECKS
// ** TpmSizeChecks()
// This function is used during the development process to make sure that the
// vendor-specific values result in a consistent implementation. When possible,
// the code contains #if to do compile-time checks. However, in some cases, the
// values require the use of "sizeof()" and that can't be used in an #if.
void
TpmSizeChecks(
    void
    );
#endif // RUNTIME_SIZE_CHECKS


#endif  // _TPMSIZECHECKS_FP_H_
