/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _TPMTOMSBNSUPPORT_FP_H_
#define    _TPMTOMSBNSUPPORT_FP_H_

#if MATH_LIB == MSBN
//*** SupportLibInit()
// This does any initialization required by the support library.
LIB_EXPORT int
SupportLibInit(
    void
    );

#ifdef COLLECT_METRICS
_REDUCE_WARNING_LEVEL_(2)
#include <stdio.h>
_NORMAL_WARNING_LEVEL_
extern memoryMetric memoryMetrics[];
#endif

//*** MathLibSimulationEnd()
// Function to print statistics
void
MathLibSimulationEnd(
    void
    );

//*** random_digits()
// Function called by MsBn to get random digits.
LIB_EXPORT BOOL WINAPI
random_bytes(
    BYTE            *result,
    size_t           count,
    bigctx_t        *ctx
    );
#endif


#endif  // _TPMTOMSBNSUPPORT_FP_H_
