/*(Copyright)
 *      Microsoft Copyright 2009 - 2015
 *      All rights reserved.
*/
/*(Auto)
    Automatically Generated by TpmPrototypes version 2.2 February 10, 2016 
    Date: Sep 22, 2016 Time: 05:27:05 PM  
*/

#ifndef    _YOYOALLOCATOR_FP_H_
#define    _YOYOALLOCATOR_FP_H_

#if MATH_LIB == MSBN
void insert_tail_list(
    list_entry      *ptail,
    list_entry      *pentry
    );

void remove_list_entry(
    list_entry  *pentry);

// initialize_simple_allocator
// with a supplied buffer
void yoyo_allocator_initialize(
    yoyo_allocator  *pallocator,
    void            *pv_buffer,
    size_t           cnt_buffer
    );

void* yoyo_allocator_alloc(
    yoyo_allocator  *pallocator,
    size_t           cnt_alloc
    );

void yoyo_allocator_free(
    yoyo_allocator  *pallocator,
    void            *pv_to_free
    );

void yoyo_allocator_uninitialize(
    yoyo_allocator  *pallocator
    );
#endif // MATH_LIB == MSBN


#endif  // _YOYOALLOCATOR_FP_H_
